### ISSUE TITLE
undefined: mku

### ISSUE THREAD

**Issue by jibanes** [ktye/i#1]
when trying to build k- with go version go1.13.1 linux/amd64.
./a.go:11:15: undefined: mku

**Comment by ktye** [comment]
it's currently broken. i'm rewriting symbol handling to allow any length. symbols are limited to 8bytes.
the last version that should work is:
98441d039334f8f602d64ab7c069a57c31ab2662

**Comment by ktye** [comment]
long symbols are completed. everything should build now.
