### ISSUE TITLE
k.go and kg.go are no longer being uploaded

### ISSUE THREAD

**Issue by pxeger** [ktye/i#20]
https://github.com/ktye/i/releases/tag/latest only has `k.c`, `k.f`, `k.wasm`, `ktye.h`, no Go files

Is this intentional?

**Comment by ktye** [comment]
yes. sorry i was not aware you were using them.
the c version that you switched to is fine. it's also tested as part of ci.

**Comment by pxeger** [comment]
Ok that's fine :)
