### ISSUE TITLE
Swapped fields in Decker fonts.deck?

### ISSUE THREAD

**Issue by 1jss** [ktye/i#28]
I had an issue importing [the fonts](https://github.com/ktye/i/blob/master/_/i2/kui/f/fonts.deck) into the font-editor. The fields for "space" and "char width" seem to be swapped. f10x20, for example has a max font width of 10, a char width of 1 and a space between characters of 10. This works when just using the font, but (if I understand it correctly) the editor expects the opposite, ie char width of 10 (on each char) and a (global) space between characters of 1.

**Comment by ktye** [comment]
i see. should i generate the fonts again, or did you fix them already?

(the bugs are here:
https://github.com/ktye/i/blob/master/_/i2/kui/f/gen.go#L94
https://github.com/ktye/i/blob/master/_/i2/kui/f/gen.go#L147 )

**Comment by 1jss** [comment]
If you have the time to regenerate them, that would be awesome!
(Thanks again for the fonts! I know they will come to great use!)

**Comment by ktye** [comment]
it should be ok now. note that the ellipsis is still missing.

other fonts that could be converted are here: https://int10h.org/oldschool-pc-fonts/ (maybe from FON files)
and openbsd console font: https://github.com/fcambus/spleen come in large sizes which is rare for raster fonts.
but all these raster formats are really a mess.

**Comment by 1jss** [comment]
Yes! Now it works perfectly! I'll see if I can add the ellipsis.

**Comment by 1jss** [comment]
I managed to add ellipsis to the fonts. Thanks!

**Comment by ktye** [comment]
thank you.
