### ISSUE TITLE
Should use argument `p`?

### ISSUE THREAD

**Issue by gitonthescene** [ktye/i#37]
Should the upper case `P` [here](https://github.com/ktye/i/blob/964edc633630078e6157ecb6c7a652f7f918b3ff/web/kweb/compile.help#L22) be lower case?

**Comment by ktye** [comment]
yes, it's called with global P so they are the same, but lowercase was intended

**Comment by gitonthescene** [comment]
Okay.  Also, on that same compile page, when I click on `asn.k` I download what looks like the tree for some other script than what's being displayed on the web site.  I was expecting to see the original code which parsed as the tree given.  Is there some other way to see the code which results in the displayed parse tree?

**Comment by ktye** [comment]
the links "asn.k" "cnd.k" "k.k" etc store the tree as a k file.
T P I S are the columns of the table.
for asn.k, *T should be \`prg and *S is \`asn.

the tables are converted form go, see
https://github.com/ktye/i/tree/master/x/tests

**Comment by gitonthescene** [comment]
I sort of see but [`asn.k`](https://github.com/ktye/i/blob/master/x/tests/asn.k) has 29 elements in its parent vector but the tree displayed has only 3: 
![C527D290-067A-470A-B487-74FFA84796A4](https://user-images.githubusercontent.com/45531702/230714885-6b158800-00cb-46e7-bea2-094767331818.jpeg)
It does say there are 29 nodes though.  Perhaps this is a rendering problem on iPhone Safari?  Actually it looks the same for Chrome and Brave.

So the 29 nodes are from parsing [this source](https://github.com/ktye/i/blob/master/x/tests/asn.go)?  I thought that was the output, like [`asn.js`](https://github.com/ktye/i/blob/master/x/tests/asn.js) or [`asn.c`](https://github.com/ktye/i/blob/master/x/tests/asn.c).

**Comment by ktye** [comment]
the function  nodes are collapsed, double-click to open.
(that should be written on the bottom of the tree)
