### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by pxeger** [ktye/i#5]
This project doesn't have a licence. Can I install it on https://ato.pxeger.com, and allow users to run their own K code in a sandbox with it? If so, can I also publish an unmodified copy as a Docker image on https://hub.docker.com?

**Comment by ktye** [comment]
it's public domain as mentioned in the readme.
you can run it everywhere.

I'm not sure how you want to install it. there are multiple possibilities:
- serve k.html, k.js, k.wasm from a static server and run client-side only (than no sandbox is needed)
- run the k.wasm from WAVM
- install the a go binary
- install the c version (see ktye/i/+) file mk as an example for building

just tell me, if you need help installing it.

**Comment by pxeger** [comment]
Oh, @ngn: https://ngn.bitbucket.io/k.html is incorrect then.

I think the go binary will be simplest, but we'll see.

Thanks!

**Comment by ktye** [comment]
@pxeger i added github actions for release building on ubuntu.
This generates source files that are easier to compile, e.g.

go (single file, does not need go.mod): 
```
wget https://github.com/ktye/i/releases/download/latest/kg.go
go build kg.go
```

c:
```
wget https://github.com/ktye/i/releases/download/latest/k.c
gcc k.c -lm
```
